version: '2'

networks:
  snapcast_nw:
  influxdb_nw:

volumes:
  snapcast:

services:
  snapserver:
    image: stilllman/snapserver:latest
    networks:
      - snapcast_nw 
    volumes:
      - snapcast:/tmp

  mopidy:
    image: stilllman/mopidy:latest
    volumes:
      - snapcast:/tmp
    environment:
      - SPOTIFY_USERNAME
      - SPOTIFY_PASSWORD
      - LASTFM_USERNAME
      - LASTFM_PASSWORD
    entrypoint:
      - "/usr/local/bin/mopidy.sh"
      - "--snapcast"


  transmission:
    image: stilllman/transmission:latest


  influxdb:
    image: influxdb:alpine
    networks:
      - influxdb_nw

  telegraf:
    image: stilllman/telegraf:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    networks:
      - influxdb_nw

  grafana:
    image: grafana/grafana
    networks:
      - influxdb_nw

  samba:
    image: stilllman/samba
    environment:
      - SAMBA_PASSWORD
