version: '2'
services:
  snapserver:
#    image: stilllman/snapserver:latest
    build: ../snapserver
    ports:
      - "1704:1704"
      - "1705:1705"
    networks:
      - snapcast_nw 
    volumes:
      - /tmp/snapcast:/tmp

  snapclient:
#    image: stilllman/snapclient:latest
    build: ../snapclient
    networks:
      - snapcast_nw
    devices:
      - /dev/snd

  mopidy:
    build: ../mopidy
    ports:
      - "6600:6600"
      - "6680:6680"
    volumes:
      - /tmp/snapcast:/tmp
    environment:
#      - SPOTIFY_USERNAME
#      - SPOTIFY_PASSWORD
      - LASTFM_USERNAME
      - LASTFM_PASSWORD
    entrypoint:
      - "/usr/local/bin/mopidy.sh"
      - "--snapcast"

  transmission:
    build: ../transmission
    ports:
      - "9091:9091"

networks:
  snapcast_nw:
    
