version: '2'

services:
  snapserver:
    ports:
      - "1704:1704"
      - "1705:1705"
    restart: always

  mopidy:
    ports:
      - "6600:6600"
      - "6680:6680"
    restart: always

  transmission:
    ports:
      - "9091:9091"
    restart: always

  influxdb:
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: always

  telegraf:
    restart: always

  grafana:
    ports: 
      - "3000:3000"
    restart: always
    env_file: grafana.env

  logspout:
    image: gliderlabs/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint:
      - /bin/logspout
      - syslog://logs4.papertrailapp.com:39618
    restart: always

