version: '2'

services:
  snapserver:
    ports:
      - "1704:1704"
      - "1705:1705"

  mopidy:
    ports:
      - "6600:6600"
      - "6680:6680"

  transmission:
    ports:
      - "9091:9091"

  influxdb:
    ports:
      - "8083:8083"
      - "8086:8086"

  grafana:
    ports: 
      - "3000:3000"

  logspout:
    image: gliderlabs/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/logspout
      - syslog://logs4.papertrailapp.com:39618

