version: '2'

networks:
  snapcast_nw:
  influxdb_nw:

volumes:
  snapcast:

services:
  snapserver:
    image: stilllman/snapserver:latest
    networks:
      - snapcast_nw 
    volumes:
      - snapcast:/tmp

  mopidy:
    image: stilllman/mopidy:latest
    volumes:
      - snapcast:/tmp
    environment:
      - SPOTIFY_USERNAME
      - SPOTIFY_PASSWORD
      - LASTFM_USERNAME
      - LASTFM_PASSWORD
    entrypoint:
      - "/usr/local/bin/mopidy.sh"
      - "--snapcast"

  lms:
    image: larsks/logitech-media-server:7.9
#    image: apnar/logitech-media-server:latest


  transmission:
    image: stilllman/transmission:latest
    environment:
      - PUID
      - PGID

  plex:
    image: linuxserver/plex:latest
    network_mode: host
    environment:
      - VERSION=latest
      - PUID
      - PGID

  sickrage:
    image: linuxserver/sickrage:latest
    environment:
      - PUID
      - PGID

  couchpotato:
    image: linuxserver/couchpotato:latest
    environment:
      - PUID
      - PGID

  influxdb:
    image: influxdb:alpine
    networks:
      - influxdb_nw

  telegraf:
    image: stilllman/telegraf:latest
    volumes:
      - /var/run:/var/run:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro # These can't be used
#      - /var/run/utmp:/var/run/utmp:ro               # otherwise there are issues with utmp
      - /proc:/hostfs/proc:ro # It seems this is needed, even though I saw no 
      - /sys:/hostfs/sys:ro   # difference with or without these
      - /etc:/hostfs/etc:ro   #
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_ETC=/hostfs/etc
      - HOST_MOUNT_PREFIX=/hostfs

    networks:
      - influxdb_nw

  grafana:
    image: grafana/grafana:latest
    networks:
      - influxdb_nw

  keeweb:
    image: antelle/keeweb

  samba:
    image: dperson/samba:latest
    network_mode: host
    environment:
      - USERID=${PUID}
      - GROUPID=${PGID}

  nextcloud:
    image: linuxserver/nextcloud:latest
    environment:
      - PUID
      - PGID

  home-assistant:
    image: homeassistant/home-assistant:latest
    network_mode: host

  hass-configurator:
    image: causticlab/hass-configurator-docker:x86_64-0.2.4

#  lychee:
#    image: linuxserver/lychee:latest
#    environment:
#      - PUID
#      - PGID

