version: '2'

services:
  snapserver:
    ports:
      - "1704:1704"
      - "1705:1705"
    restart: always #unless-stopped

  mopidy:
    ports:
      - "6600:6600"
      - "6680:6680"
    restart: always

  lms:
    environment:
      - TZ=Europe/Paris
    ports:
      - "9000:9000"
      - "9090:9090"
      - "3483:3483"
      - "3483:3483/udp"
    volumes:
      - /mnt/data:/data
    restart: always

  transmission:
    ports:
      - "9091:9091"
      - "51413:51413"
    volumes:
      - /mnt/appdata/transmission:/config
      - /mnt/data:/data # must be the same as sickrage/plex/sonarr/couchpotato etc.
                        # Also a single mount point is needed for hardlinks to work
    restart: always

  plex:
    volumes:
      - /mnt/appdata/plex:/config
      - /mnt/data:/data
    restart: always

  # sickrage:
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - /mnt/appdata/sickrage:/config
  #     - /mnt/data:/data
  #   restart: always
  sonarr:
    ports:
      - "8989:8989"
    volumes:
      - /mnt/appdata/sonarr:/config
      - /mnt/data:/data
    restart: always

  couchpotato:
    ports:
      - "5151:5050"
    volumes:
      - /mnt/appdata/couchpotato:/config
      - /mnt/data:/data
    restart: always

  jackett:
    ports:
      - "9117:9117"
    volumes:
      - /mnt/appdata/jackett:/config
    restart: always

  # influxdb:
  #   ports:
  #     - "8083:8083"
  #     - "8086:8086"
  #   restart: always

  # telegraf:
  #   restart: always

  # grafana:
  #   ports: 
  #     - "3000:3000"
  #   restart: always
  #   env_file: grafana.env

  keeweb:
    ports:
      - "1234:80"
      - "1235:443"
    restart: always

  samba:
    ports:
      - "137-139:137-139"
      - "145:145"
    volumes:
      - /mnt/data:/data
    entrypoint:
      - samba.sh
      - -n
      - -s
      - data;/data;yes;no;no;samba;none
      - -u
      - samba;${SAMBA_PASSWORD}
    restart: always

  nextcloud:
    ports: 
      - "443:443"
    volumes:
      - /mnt/appdata/nextcloud:/config
      - /mnt/data:/local-data
    restart: always

  home-assistant:
    ports:
      - "8123:8123"
    volumes:
      - /mnt/appdata/home-assistant:/config
    restart: always

  hass-configurator:
    ports:
      - "3218:3218/tcp"
    volumes:
      - /mnt/appdata/home-assistant:/config
      - /mnt/appdata/hass-configurator:/hass-config
    restart: always

#  lychee:
#    ports:
#      - "1259:80"
#    volumes:
#      - /mnt/appdata/lychee:/config
#      - /mnt/data/photos:/photos # not used by lychee but by lycheesync
#    restart: always

  logspout:
    image: gliderlabs/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint:
      - /bin/logspout
      - syslog://logs4.papertrailapp.com:39618
    restart: always

  portainer:
    image: portainer/portainer
    ports:
      - "2121:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/appdata/portainer:/data
    restart: always