version: '2'

services:
  snapserver:
    ports:
      - "1704:1704"
      - "1705:1705"
    restart: always #unless-stopped

  mopidy:
    ports:
      - "6600:6600"
      - "6680:6680"
    restart: always

  transmission:
    ports:
      - "9091:9091"
      - "51413:51413"
    volumes:
      - /home/rancher/appdata/transmission:/config
      - /mnt/data/downloads:/downloads
    restart: always

  plex:
    volumes:
      - /home/rancher/appdata/plex:/config
      - /mnt/data/series:/data/series
      - /mnt/data/films:/data/films
      - /mnt/data/photos:/data/photos
      - /mnt/data/videos:/data/videos
    restart: always

  sickrage:
    ports:
      - "8081:8081"
    volumes:
      - /home/rancher/appdata/sickrage:/config
      - /mnt/data/downloads:/downloads
      - /mnt/data/series:/tv
    restart: always

  influxdb:
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: always

  telegraf:
    restart: always

  grafana:
    ports: 
      - "3000:3000"
    restart: always
    env_file: grafana.env

  samba:
    ports:
      - "137-139:137-139"
      - "145:145"
    volumes:
      - /mnt/data:/data
    entrypoint:
      - samba.sh
      - -n
      - -s
      - data;/data;yes;no;no;samba;none
      - -u
      - samba;${SAMBA_PASSWORD}
    restart: always

  owncloud:
    ports: 
      - "1258:80"
    volumes:
      - /mnt/data:/data

  logspout:
    image: gliderlabs/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint:
      - /bin/logspout
      - syslog://logs4.papertrailapp.com:39618
    restart: always
