version: '2'
services:
  
  snapserver:
#    image: stilllman/snapserver:latest
    build: ../snapserver
    ports:
      - "1704:1704"
      - "1705:1705"
    networks:
      - snapcast_nw 
    volumes:
      - /tmp/snapcast:/tmp

  snapclient:
#    image: stilllman/snapclient:latest
    build: ../snapclient
    networks:
      - snapcast_nw
    devices:
      - /dev/snd

  mopidy:
    build: ../mopidy
    ports:
      - "6600:6600"
      - "6680:6680"
    volumes:
      - /tmp/snapcast:/tmp
    environment:
#      - SPOTIFY_USERNAME
#      - SPOTIFY_PASSWORD
      - LASTFM_USERNAME
      - LASTFM_PASSWORD
    entrypoint:
      - "/usr/local/bin/mopidy.sh"
      - "--snapcast"


  transmission:
    build: ../transmission
    ports:
      - "9091:9091"


  influxdb:
    image: influxdb:alpine
    ports:
      - 8083:8083
      - 8086:8086
    networks:
      - influxdb_nw
    volumes:
      - /home/influxdb:/var/lib/influxdb

  telegraf:
    build: ../telegraf
    networks:
      - influxdb_nw

  grafana:
    image: grafana/grafana
    ports: 
      - 3000:3000
    networks:
      - influxdb_nw


networks:
  snapcast_nw:
  influxdb_nw:
    
