version: '2'

services:
  snapserver:
    ports:
      - "1704:1704"
      - "1705:1705"
    restart: always #unless-stopped

  mopidy:
    ports:
      - "6600:6600"
      - "6680:6680"
    restart: always

  lms:
    environment:
      - TZ=Europe/Paris
    ports:
      - "9000:9000"
      - "9090:9090"
      - "3483:3483"
      - "3483:3483/udp"
    volumes:
      - /mnt/data:/data
    restart: always

  transmission:
    ports:
      - "9091:9091"
      - "51413:51413"
    volumes:
      - /home/rancher/appdata/transmission:/config
      - /mnt/data/downloads:/downloads
      - /mnt/data/series:/tv # must be the same as sickrage
      - /mnt/data/films:/movies # must be the same as couchpotato
    restart: always

  plex:
    volumes:
      - /home/rancher/appdata/plex:/config
      - /mnt/data/series:/data/series
      - /mnt/data/films:/data/films
      - /mnt/data/photos:/data/photos
      - /mnt/data/videos:/data/videos
    restart: always

  sickrage:
    ports:
      - "8081:8081"
    volumes:
      - /home/rancher/appdata/sickrage:/config
      - /mnt/data/downloads:/downloads
      - /mnt/data/series:/tv # must be the same as transmission
    restart: always

  couchpotato:
    ports:
      - "5151:5050"
    volumes:
      - /home/rancher/appdata/couchpotato:/config
      - /mnt/data/downloads:/downloads
      - /mnt/data/films:/movies # must be the same as transmission
    restart: always

  influxdb:
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: always

  telegraf:
    restart: always

  grafana:
    ports: 
      - "3000:3000"
    restart: always
    env_file: grafana.env

  keeweb:
    ports:
      - "1234:80"
      - "1235:443"
    restart: always

  samba:
    ports:
      - "137-139:137-139"
      - "145:145"
    volumes:
      - /mnt/data:/data
    entrypoint:
      - samba.sh
      - -n
      - -s
      - data;/data;yes;no;no;samba;none
      - -u
      - samba;${SAMBA_PASSWORD}
    restart: always

  nextcloud:
    ports: 
      - "443:443"
    volumes:
      - /home/rancher/appdata/nextcloud:/config
      - /mnt/data:/local-data
    restart: always

  home-assistant:
    ports:
      - "8123:8123"
    volumes:
      - /home/rancher/appdata/home-assistant:/config
    restart: always

  hass-configurator:
    ports:
      - "3218:3218/tcp"
    volumes:
      - /home/rancher/appdata/home-assistant:/config
      - /home/rancher/appdata/hass-configurator:/hass-config
    restart: always

#  lychee:
#    ports:
#      - "1259:80"
#    restart: always

  logspout:
    image: gliderlabs/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint:
      - /bin/logspout
      - syslog://logs4.papertrailapp.com:39618
    restart: always
