version: '2'

services:
  snapserver:
    build: ../snapserver
    ports:
      - "1704:1704"
      - "1705:1705"

  snapclient:
    image: stilllman/snapclient:latest
    build: ../snapclient
    networks:
      - snapcast_nw
    devices:
      - /dev/snd

  mopidy:
    build: ../mopidy
    ports:
      - "6600:6600"
      - "6680:6680"

  lms:
    build: ../docker-image-logitech-media-server
    ports:
      - 9000:9000
      - 9090:9090
      - 3483:3483
      - 3483:3483/udp
    volumes:
      - /home/osboxes/Music:/srv/music


  transmission:
    build: ../transmission
    ports:
      - "9091:9091"
    volumes:
      - /tmp/transmission-docker:/downloads

  plex:
    build: ../docker-plex
    volumes:
      - /home/osboxes/data/videos:/data/series

  sickrage:
    build: ../docker-sickrage
    ports:
      - "8081:8081"
    volumes:
      - /home/osboxes/data/videos:/tv
      - /home/osboxes/data/downloads:/downloads

  couchpotato:
    ports:
      - "5050:5050"
    volumes:
      - /home/osboxes/data/films:/movies
      - /home/osboxes/data/downloads:/downloads

  influxdb:
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /home/influxdb:/var/lib/influxdb

  telegraf:
    build: ../telegraf

  grafana:
    ports: 
      - "3000:3000"

  keeweb:
    ports:
      - "1234:80"
      - "1235:443"

  samba:
    ports:
      - "137-139:137-139"
    volumes:
      - /home/osboxes/Videos:/data
    entrypoint:
      - samba.sh
      - -n
      - -s
      - data;/data;yes;no;no;samba;none
      - -u
      - samba;foobar;1005

  nextcloud:
    ports: 
      - "443:443"
    volumes:
      - /home/osboxes/Videos:/local-data

#  lychee:
#    ports:
#      - "8087:80"
